### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by appositum** [joooooooooooooooooooooooooooooooooooooj/jooj#4]
Jason is obviously too cliche for a JSON parser and there's already a package with that same name for that same purpose.

**Comment by sqdorte** [comment]
what about JOOJ?
**JO**nathan's **O**k **J**son parser :+1:

**Comment by appositum** [comment]
**J**ooj's
**O**verly
**O**dd
**J**son parser

Then transfer the repository to [jooj](https://github.com/joooooooooooooooooooooooooooooooooooooj/)

**Comment by appositum** [comment]
Done #5
